[package]
name = "bevy_pane_layout"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy.workspace = true
bevy_editor_styles.workspace = true
bevy_3d_viewport.workspace = true

[lints]
workspace = true
