[package]
name = "bevy_pane_layout"
version = "0.1.0"
edition = "2024"


[dependencies]
bevy.workspace = true
bevy_editor_styles.workspace = true
bevy_context_menu.workspace = true

[lints]
workspace = true
