[package]
name = "bevy_menu_bar"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_editor_palette = { path = "../../crates/bevy_editor_palette" }

[lints]
workspace = true
