[package]
name = "bevy_menu_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_editor_styles.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc-rs.workspace = true
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true


[lints]
workspace = true
