[package]
name = "bevy_editor_pls_core"
version.workspace = true
edition.workspace = true
license.workspace = true 

[dependencies]
bevy = { version = "0.13", default-features = false }
bevy-inspector-egui.workspace = true
indexmap = "2"
egui_dock.workspace = true
