[package]
name = "bevy_2d_viewport"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_pane_layout.workspace = true
bevy_editor_camera.workspace = true
bevy_editor_styles.workspace = true
bevy_infinite_grid.workspace = true

[lints]
workspace = true
