[package]
name = "bevy_text_field"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_focus.workspace = true
bevy_editor_styles.workspace = true

arboard = "3.4.1"

[lints]
workspace = true
