[package]
name = "bevy_numeric_field"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_text_field.workspace = true
bevy_focus.workspace = true
num-traits = "0.2.19"

[lints]
workspace = true
