[package]
name = "TESTProject"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "015f2c69ca2a2c009fd04eadada282482deaf469", features = ["wayland"] }
bevy_editor = { path = "../bevy_editor/crates/bevy_editor/" }
